name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.5
    - name: Gradle Command
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build

